### ISSUE TITLE
Update documentation link

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/wps-gui#225]
The documentation link at https://github.com/boundlessgeo/wps-gui/blob/master/src/wpsui.js#L46 will need to be updated for Suite 4.9 - we are no longer using `opengeo-docs` and have instead switched to `suite-docs`

**Comment by bartvde** [comment]
thanks for heads-up @tbarsballe do I need to update the submodule as well in suite?

**Comment by tbarsballe** [comment]
Yes please.

**Comment by bartvde** [comment]
@tbarsballe just to confirm, there is no 4.9 release branch, so in master?

**Comment by tbarsballe** [comment]
Yes, suite is currently using master

**Comment by bartvde** [comment]
Done with https://github.com/boundlessgeo/suite/commit/e83f0785ee73735313bba77b302c6927c5a3679c
