### ISSUE TITLE
marshaller / unmarshaller not initialized

### ISSUE THREAD

**Issue by spike83** [boundlessgeo/wps-gui#226]
I had the problem the marshaller and unmarshaller was not initialized.

So I quick and dirty changed with examples found elsewhere in the file.

https://github.com/spike83/wps-gui/commit/1b7288ae821ff556daca6237b9d026b79578ae90#diff-a4cb027927a4d2aa305f0fe2086cdac2R200
https://github.com/spike83/wps-gui/commit/1b7288ae821ff556daca6237b9d026b79578ae90#diff-a4cb027927a4d2aa305f0fe2086cdac2R301

Is this a known bug? Or what was going wrong?

**Comment by bartvde** [comment]
Do you get into this line: https://github.com/boundlessgeo/wps-gui/blob/master/src/wpsclient.js#L679 or maybe WFS GetCapabilities is slow in your case? Any guidance on this will help find the correct fix for it. TIA.

**Comment by spike83** [comment]
Sorry for the delay. You are right L679 is not hit in my case. The response is not extrem slow, about 500ms when fetching in browser.

**Comment by bartvde** [comment]
@spike83 are you able to debug through the code to see why L679 is not hit? Maybe reponseXML is not defined but responseText is?

**Comment by spike83** [comment]
@bartvde sure, I saw, that the line is called with my prod env wps. So I was digging deeper and saw the diffrence is that on my dev box the line https://github.com/boundlessgeo/wps-gui/blob/master/src/wpsclient.js#L669 is called but the info.featureTypeList.featureType is undefined.
In my dev geoserver (which produces the problem) are no vector layers.
If i add one its working as expected. So the L679 may unnecessarily depends on existence of wfs features?
